# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'BeeBloom' do
	project 'BeeBloom.xcodeproj'
	pod 'OneSignalXCFramework', '3.11.2'
	pod 'Firebase/Messaging', '~> 8.1.1'
	pod 'GoogleSignIn', '~> 5.0.2'
	pod 'GoogleUtilities', '~> 7.7'
	pod 'Google-Mobile-Ads-SDK', '~> 8.13.0'
	pod 'GoogleUserMessagingPlatform', '~> 2.0.0'
	pod 'razorpay-pod'
end
